# Generated by Django 5.1 on 2024-11-11 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juguete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion del producto')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('codigoProducto', models.CharField(max_length=20, verbose_name='Código del Producto')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Juguete',
                'verbose_name_plural': 'Juguetes',
                'db_table': 'juguete',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion del producto')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('codigoProducto', models.CharField(max_length=20, verbose_name='Código del Producto')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'libro',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion del producto')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('codigoProducto', models.CharField(max_length=20, verbose_name='Código del Producto')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Ropa',
                'verbose_name_plural': 'Ropas',
                'db_table': 'ropa',
                'ordering': ['nombre'],
            },
        ),
    ]
