# Generated by Django 5.1 on 2024-11-12 05:46

import pruebaApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juguete',
            name='foto',
            field=models.ImageField(blank=True, default='juguetes/juguete.png', null=True, upload_to=pruebaApp.models.Juguete.generar_nombre),
        ),
    ]
